export const GET_ALL_REPORT_REQUEST = 'GET_ALL_REPORT_REQUEST';
export const GET_ALL_REPORT_SUCCESS = 'GET_ALL_REPORT_SUCCESS';
export const GET_ALL_REPORT_ERROR = 'GET_ALL_REPORT_ERROR';

export const GET_TOTAL_CULCALATOR_REQUEST = 'GET_TOTAL_CULCALATOR_REQUEST';
export const GET_TOTAL_CULCALATOR_SUCCESS = 'GET_TOTAL_CULCALATOR_SUCCESS';
export const GET_TOTAL_CULCALATOR_ERROR = 'GET_TOTAL_CULCALATOR_ERROR';

export const GET_QUERY_REPORT_REQUEST = 'GET_QUERY_REPORT_REQUEST';
export const GET_QUERY_REPORT_SUCCESS = 'GET_QUERY_REPORT_SUCCESS';
export const GET_QUERY_REPORT_ERROR = 'GET_QUERY_REPORT_ERROR';

