export const LOGIN = 'app/App/LOGIN';
export const LOGIN_SUCCESS = 'app/App/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'app/App/LOGIN_FAILED';
export const LOGOUT = 'app/App/LOGOUT';
export const GET_CURRENT_USER = 'app/App/GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_PERMISSIONS = 'GET_SELECT_PERMISSIONS';
export const GET_PERMISSIONS_SUCCESS = 'GET_SELECT_PERMISSIONS_SUCCESS';
export const GET_PERMISSIONS_FAILED = 'GET_PERMISSIONS_FAILED';

export const GET_CHECKBOX = 'GET_CHECKBOX';
export const GET_CHECKBOX_SUCCESS = 'GET_CHECKBOX_SUCCESS';
export const GET_CHECKBOX_FAILED = 'GET_CHECKBOX_FAILED';
